<?php
namespace asinfotrack\yii2\flagicons\implementations;

use asinfotrack\yii2\flagicons\widgets\FlagIcon;

/**
 * Wrapper class to allow for chaining of methods and generation
 * of the flag widget
 *
 * @author Pascal Mueller, AS infotrack AG
 * @link http://www.asinfotrack.ch
 * @license MIT
 */
class FlagWrapper extends \yii\base\Object
{

	/**
	 * @var string the tag-name to use
	 */
	protected $tagName = 'span';

	/**
	 * @var bool whether or not the flag should be square
	 */
	protected $isSquared = false;

	/**
	 * @var string the mandatory country code consisting of two characters
	 */
	public $countryCode;

	/**
	 * @var array options for the enclosing tag
	 */
	public $options = [];

	/**
	 * Sets the tag name which will be used (defaults to span)
	 *
	 * @param string $tagName the tag name to use
	 * @return \asinfotrack\yii2\flagicons\implementations\FlagWrapper self for chaining
	 */
	public function tagName($tagName)
	{
		$this->tagName = $tagName;
		return $this;
	}

	/**
	 * Sets whether or not to use squared flags (defaults to false)
	 *
	 * @param bool|true $isSquared
	 * @return $this
	 */
	public function squared($isSquared=true)
	{
		$this->isSquared = $isSquared;
		return $this;
	}

	/**
	 * Generates the actual html for the flag icon. This method will
	 * generate an instance of the FlagIcon widget and return the code
	 * @see \asinfotrack\yii2\flagicons\widgets\FlagIcon
	 *
	 * @return string the resulting html code as generated by the widget
	 * @throws \Exception
	 */
	function __toString()
	{
		return FlagIcon::widget([
			'countryCode'=>$this->countryCode,
			'options'=>$this->options,
			'tagName'=>$this->tagName,
			'isSquared'=>$this->isSquared,
		]);
	}

}
